vich_uploader:
   db_driver: orm

   mappings:
      images_actu:
         uri_prefix: /images/actu
         upload_destination: "%kernel.project_dir%/public/images/actu"
         namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      images_machines:
         uri_prefix: /images/machines
         upload_destination: "%kernel.project_dir%/public/images/machines"
         namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      images_album:
         uri_prefix: /images/album
         upload_destination: "%kernel.project_dir%/public/images/album"
         namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      pdf_files:
         uri_prefix: /images/pdf
         upload_destination: "%kernel.project_dir%/public/images/pdf"
         namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
